### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by tjerram** [hominoids/SBC_Case_Builder#17]
I followed the instructions but get the following error:

 git submodule update
Cloning into '/home/pi/SBC_Case_Builder/SBC_Model_Framework'...
Warning: Permanently added the ECDSA host key for IP address '140.82.113.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hominoids/SBC_Model_Framework.git' into submodule path '/home/pi/SBC_Case_Builder/SBC_Model_Framework' failed
Failed to clone 'SBC_Model_Framework'. Retry scheduled
Cloning into '/home/pi/SBC_Case_Builder/SBC_Model_Framework'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:hominoids/SBC_Model_Framework.git' into submodule path '/home/pi/SBC_Case_Builder/SBC_Model_Framework' failed
Failed to clone 'SBC_Model_Framework' a second time, aborting

**Comment by tomek-szczesny** [comment]
The problem is probably with the contents of `.gitmodules`:
https://github.com/hominoids/SBC_Case_Builder/blob/d59191109eca048a00e6223cadb4dc60156d6857/.gitmodules#L3

Try replacing that line with the following:
`url = https://github.com/hominoids/SBC_Model_Framework.git`

This is because ssh access requires valid credentials, and https access is available to everyone, albeit read only.

**Comment by hominoids** [comment]
I changed the .gitmodules entry in main to https access. Thanks tjerram for reporting the issue and thanks Tom for the fix.  I'm leaving this open temporarily until it gets rolled into a release.

**Comment by hominoids** [comment]
I think this can be closed now.
