### ISSUE TITLE
Adding new boards?

### ISSUE THREAD

**Issue by Botched1** [hominoids/SBC_Case_Builder#18]
Just learned about this - installed it, and it is great! Very nice work.

Question - how hard is it to add new boards, and is that something end users can do? For instance I use a lot of RAKWireless WisBlock boards to make IoT devices, and this could potentially be a great tool to use for case design on those.

If it is something an end user can do, I would be open to making a try at doing it.

Example board:
https://store.rakwireless.com/products/rak19007-wisblock-base-board-2nd-gen

They also have 3D models for most of their stuff. Example:
https://downloads.rakwireless.com/3D_File/WisBlock/3D_RAK19007.stp

**Comment by hominoids** [comment]
Boards are added in SBC Model Framework and there is a write up on the basic process at the HK forum thread.
https://forum.odroid.com/viewtopic.php?f=53&t=33823
Regarding SBC Case Builders use with new boards, as long as no new components are needed the integration is fairly straight forward.  The Customizer’s SBC list needs to be updated.  If new SBC components are needed then new components are created in sbc_library.scad and masks openings in sbc_case_builder_library.scad in the module mask().

Right now it won’t be possible to use SBC Model Framework or SBC Case Builder for complex PCB shapes because they are not supported.  I have been looking at ways to implement that capability, as well as other improvements for SBC Model Framework, so possibly in the future.

**Comment by Botched1** [comment]
That is awesome! Great work.

**Comment by samuk** [comment]
Would you be interested in adding a case for: https://pipci.jeffgeerling.com/boards_cm/johanns_carrier_board.html I hope to make them available for sale soon. The boards will be CERN-OHL-P open hardware

The step is https://github.com/samuk/Open-Pi/tree/main/v1/3d

**Comment by hominoids** [comment]
Hi Samuk,
It is possible but please open a new issue to discuss this topic further 
regarding your specific request.

hominoid

**Comment by hominoids** [comment]
It's been awhile but I wanted to let you know  version 2 of SBC Model Framework has been released and that this has been completed, in case your still interested.  A complete rk19007 has been added to SBC Model Framework and subsequently SBC Case Builder.  I used the RAK STEP model converted to STL to locate the components, others can be created the same way.
```
use <./sbc_models.scad>
model = "rak19007";

import("RAK19007_VB_0330.stl");
sbc(model, "default", 0, "default", "default", false);
// uncomment for mask set
//#sbc(model, "default", 0, "default", "default", true);
```
![rak19007](https://github.com/hominoids/SBC_Case_Builder/assets/37256300/b945d343-fffe-4b68-b9aa-74756494dfb7)
