### ISSUE TITLE
a way to just  render case top or bottom

### ISSUE THREAD

**Issue by gjm19761** [hominoids/SBC_Case_Builder#19]
For People with smaller build plates is it possible to render the top or the bottom as individual renders ??

**Comment by Nurb432** [comment]
Just go into the design in SCAD and only export one piece at a time.

**Comment by gjm19761** [comment]
i dont see that option under export anywhere in scad?

**Comment by Nurb432** [comment]
i will verify the parameter tonight, but if i remember right its "offset" on the object, and if you set to < 1 it hides it. Then it only exports the one piece.

**Comment by hominoids** [comment]
I use Slic3r's split function to breakout the individual pieces.  One of the problems is that the platters are generated dynamically so the amount of pieces and the overall size varies considerably.  The process that @Nurb432 suggested is a good work around in some situations but won't work correctly all the time.  Many of the pieces won't be in the correct orientation to print so they would still need to be transformed again.  It won't handle any of the components from accessories correctly either.

Using debug view might work. I use it to work on individual pieces during development.  I think I can add a pick box for what piece to generate when debug is selected and then they would be in the right orientation for printing.   I'll take a look and let you know how it goes. 

One other thing, Not sure what SBC you guys are using but, if anyone can help verify any of the SBC not yet verified in SBC Model Framework I would really appreciate it.  It involves simply printing a shell case for the SBC and making or letting me know what corrections are needed for sbc_models.cfg.  Unfortunately I can not own them all to do the work, I wish I could.

**Comment by tomek-szczesny** [comment]
Would be handy to find a way outside of slicer. I don't own a 3D printer and just export stuff from OpenSCAD so other can print them for me.
A checkbox for displaying separate parts, well oriented for printing, would be great.
But if the script could automatically export all parts to stl format separately that'd be perfect. However I'm not sure if stl exports can be automated in OpenSCAD language.

**Comment by hominoids** [comment]
I added part selection for 'debug' and setup the case parts to display at  the origin for all parts accept the accessories.  Their platter location is stored in the sbc_case_builder_accessories.cfg and are placed accordingly.  I think this will work fine for individual parts but I'll keep an open mind to other ideas. let me know if there are any issues with the current implemented approach or other brainstorms.
Tom, thanks for the input.  I though about using check boxes but they are placed vertical when there is more then one and it would take more room and might not be the best UI layout.  It also would complicate the platter creation since it would be totally dynamic and I would have to start looking at part size to be guaranteed a proper and usable platter layout for any given part combination.  I'm not sure it's worth the extra effort over the current approach.
