### ISSUE TITLE
Generating heat sinks?

### ISSUE THREAD

**Issue by gounthar** [hominoids/SBC_Case_Builder#30]
Hi there! 👋

I have been following this repository for a few months now, and I am thrilled that it exists. Your work is impressive, and I want to thank you for it. I have also been working on building a generic library with OpenSCAD to create boxes based on SBC dimensions, rack units, and more. However, your library is lightyears ahead of mine, and I truly appreciate your contribution.

One of the things I had in mind for my library was a heatsink generator. Unfortunately, I lacked many measurements to make it effective and ensure it fits as many components as possible. My plan was to print a thin prototype in PLA to test the fit (even in translucent PLA) and then use my CNC (yes, I got one just for this purpose) to mill a large heatsink block.

So, my question is, do you think your models have enough measurements to create a custom heatsink for each board?

Thank you so much for your time and expertise. Your work has been inspiring, and I look forward to your response.

**Comment by hominoids** [comment]
Well, that is an interesting and a complicated question but I believe the short answer is probably.  The library involved would be SBC Model Framework not SBC Case Builder.  Let me explain how things work now and where development is going.  In essence, what your suggesting is what happens right now for some SBC.  Some heatsink models are generate on the fly with OpenSCAD and some are models provided by the manufacturer converted to a STL.  My goal is to have them all automatically generated but using OEM models has allowed me to offer heatsinks I haven’t had time to work on yet. See the [heatsink class in sbc_library.scad](https://github.com/hominoids/SBC_Model_Framework/blob/616edae8cb62fea0a4a067d471a521597516b81c/sbc_library.scad#L1950)

If there is an OEM heatsink they are handled as their own entry in sbc_models.cfg as x_loc,y_loc,rotation,class,type for model inclusion.  If there is no official OEM heatsink one is not displayed(RPI) or, in some cases were there is a wide and clear community driven choice, it is included. e.g. using XU4 and XU4Q heatsinks on the StarFive2 or ROCK5B.

            ["c1+",85,56,1,3.5,17,6,                                // sbc model, pcb size and component height
            3.5,3.5,3,3.5,52.5,3,                                   // pcb holes 1 and 2
            61.5,3.5,3,61.5,52.5,3,                                 // pcb holes 3 and 4
            9.385,38,3,60.615,18,3,                                 // pcb holes 5 and 6
            0,0,0,0,0,0,                                            // pcb holes 7 and 8
            0,0,0,0,0,0,                                            // pcb holes 9 and 10             
            12,12,1.25,34.4,22,0,0,"top",                           // soc1 size, location, rotation and side
            0,0,0,0,0,0,0,"",                                       // soc2 size, location, rotation and side
            0,0,0,0,0,0,0,"",                                       // soc3 size, location, rotation and side
            0,0,0,0,0,0,0,"",                                       // soc4 size, location, rotation and side
 	.
	.
	.
	9.385,38,0,"top","heatsink","c1+_oem"],                 // heatsink

In the partial [C1+ entry](https://github.com/hominoids/SBC_Model_Framework/blob/616edae8cb62fea0a4a067d471a521597516b81c/sbc_models.cfg#L101) above, the x,y location is relative to the heatsink origin, which can vary between heatsinks and be defined anywhere, and is usually set based on the SOC location.  There is also heatsink hole data in the fixed length portion of the SBC definition.  SBC Model Framework requires the first hole entries to be the main PCB mounting holes for the case and generally speaking the heatsink holes are defined afterwards.  So in the above example the heatsink hole location and size are indicated by holes 5 and 6.  The height of the SOC is also given in the SOC1 entry as 1.25mm. See [file format documentation](https://github.com/hominoids/SBC_Model_Framework/blob/main/README.md).

So one could use the SBC data in SBC Model Framework to know the heatsink hole locations and pattern as well as the proper x,y,z location to place the heatsink in reference to the SOC.  This information could be queried for use during the design process and then again in a checking and locating process to validate the design and check for other component interference.

To do this there are several challenges that currently exist but all of them can be overcome.

- Missing SOC data for an entry.
- Correctly identify the heatsink holes from other holes.
- Better PCB component representation.

SOC information in some instantaneous is not provided by the OEM(e.g. RPI) but can be acquired with some effort.  It is the most common reason why SBC Model Framework models are “yellow” and not verified “green”.  The SOC data isn’t necessarily required for case generation so not a big impact on SBC Case Builder.  Knowing what hole entries belong to the heatsink needs to be improved so when a PCB was more then 4 mount holes or other holes, the heatsink holes can be clearly identified.   Also, to reduce space and improve performance many SBC components have been generalized and may not be accurate in the depth of the component, which will be an issue for accurate internal SBC interference checking.  These are all identified shortcomings of version 1 of SBC Model Framework and are being addressed in version 2 currently in the SBC Model Framework branch v2update.

There are other new features and more complete and accurate library components being introduced for version 2 which will also incorporate complex PCBs and dynamic component masks.  Most of the code is done and I have been slowly working on converting all the SBC to the new format.  It should have been done by now but I stopped working on it to help with a couple of other open source projects. I hope to be back on it again soon and finish it up.  Some other information is available at the [HK forum where I write about it](https://forum.odroid.com/viewtopic.php?f=53&t=33823&start=52) sometimes.


To summarize, you could use SBC Model Framework to extract heatsink hole and placement location data to use in a heatsink design algorithm and then place the heatsink design on the same SBC model for checking and locating, either manually or autonomously.  Take a look at how SBC Case Builder searches for the selected SBC and uses the data from SBC Model Framework. The same approach can be used in your heatsink algorithm to access the needed SBC data.

It is also possible to easily integrate your heatsink algorithm into SBC Model Framework as another type of heatsink that can be used on a SBC.  The benefit of doing this is that in version 2, the opening masks are being moved from SBC Case Builder to SBC Model Framework as part of the SBC model.  What this means is automatic opening generation at the model level.  Any use of the SBC model in any design also makes an IO opening mask set available to difference against  geometry for accurate and consistent SBC openings.  Since heatsinks are considered a SBC component their opening mask is also available to use.  This means your heatsinks could work with SBC Case Builder or other future downstream application that use any SBC model from SBC Model Framework. See examples of [version 2 automatic mask generation](https://forum.odroid.com/viewtopic.php?f=53&t=33823&start=54).

**Comment by gounthar** [comment]
Thanks for taking the time to provide such a detailed and insightful response to my question. Your explanation of the SBC Model Framework and how it handles heatsinks was incredibly helpful, and I truly appreciate all the pointers you gave me.

I must admit that my OpenSCAD skills are still at a beginner level, and I realize that creating code up to your standards might be challenging for me at the moment. However, I am eager to learn and progress in this area.

I will study your answer thoroughly and try to understand how I can make use of the SBC Model Framework to extract heatsink hole and placement location data for my project. The idea of integrating my heatsink algorithm (which only exists in pseudo-code in my head) into the framework as another type of heatsink sounds intriguing, and I will explore that possibility further.

**Comment by hominoids** [comment]
Attached is a simple routine that searches sbc_models.cfg and prints to the console the sbc data for the requested SBC model.  It will help get you going.  I'll close this issue for now but reopen it if needed.
[SBCMF_skeleton.zip](https://github.com/hominoids/SBC_Case_Builder/files/12210216/SBCMF_skeleton.zip)
