### ISSUE TITLE
Missing Reset Button on Star64

### ISSUE THREAD

**Issue by Fishwaldo** [hominoids/SBC_Case_Builder#34]
Hi,
Just some feedback - The star64 model is missing the reset button between the USB jacks and the headphone jack. I've attached a image here for your reference. 
![Star64-SBC-1](https://github.com/hominoids/SBC_Case_Builder/assets/842308/97cb14ce-cdd2-4459-82d7-8b47ade069db)

You can see it on the top left.

**Comment by hominoids** [comment]
Thanks for the feedback, I don't have one of these SBC.  Can you post a measurement here from the top of the PCB to the top edge of the button or make the change in SBC Model Framework and issue a PR?  It looks like there are two IPEX connectors next to it as well that aren't on the model which I'll also add.  Any other corrections or additions?

**Comment by Fishwaldo** [comment]
Hi, I tried to make the changes but failed miserably. Here is some measurements. 

![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/ab9a89be-e4cc-423e-8146-534ba90ea49a)

![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/bd0fee92-b344-419e-a425-075c969c32b6)

**Comment by Fishwaldo** [comment]
Anything else you need?

**Comment by Fishwaldo** [comment]
Ahhh. Sorry I was confused about the "top" of the board. Here is another pic ![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/d9e33af1-a923-4082-a333-f8d725fc04e1)

A few other things (that might be relevant?)

The Ethernet port is stacked, and by default exceeds the height of the cases. Here is the height of the Ethernet jacks: 
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/a55e02ff-5d5c-4d47-8453-bf27d8d4c875) (I just increased the top half by 13 or 14 (if I went to 15, the cutouts for the vent disappeared but 15 would have been nice clearance) 

Also, the PCI connector exceeds the width of the PCB by 1-2mm, and is a tight fit with the side of the case. Maybe increase the width a little bit?
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/34ad01eb-0ec1-4b7d-9618-a3ba64d79a59)

Final point, the bottom of the USB jacks also exceed the length of the board and need a cutout on the bottom of the cases, otherwise the PCB doesn't rest on the standoffs but on the edge of the bottom of the case. Maybe just increase the height of the standoffs by default? 
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/a356f1d8-703b-4315-876c-10b58ad88777)

Last issue: the cutout for the HDMI port should be moved a slight bit lower. It ended up printing as below:![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/67ab89ee-4528-4a67-86fc-e70e519d7747)
(HDMI port also rests on the bottom side of the case) 

(Cheers for your assistance, I know a lot of people have been asking for a case for the star64!)

**Comment by Fishwaldo** [comment]
Sorry 2 other small things:
This might not be an issue when the reset button is done, but right now, the length of the case is a bit small, and it rests on top of the reset button... ![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/a0111479-2725-4d1f-9c84-92d65b113bee) (hard to see with black PLA, sorry) 

Also, the SD card slot is too low (the top of the slot needs to align with the top of the standoffs) and it needs to move slightly right when looking from the side:
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/0a67e12c-0334-46e2-8a43-afa3df2b972f)

**Comment by Fishwaldo** [comment]
That last picture is from the right edge of the slot to the edge of the board.

**Comment by hominoids** [comment]
Great, that's the type of feedback I need.  It looks like the PCB thickness may be incorrect since it is sitting slightly recessed in the case bottom. The top of the PCB surface should be even with the top edge of the case bottom.  Component openings in both case halves are made automatically as needed.  When it is off it can cause similar problems to what your reporting.  What is the PCB thickness?  It also looks like the gap, the distance between the PCB and case wall, may need to be increased in SBCCB.

 I'll make all these changes and include a saved case example for you to try.  The test case will tell me critical info and in the end we'll end up with a verified SBC model that will work for all the case designs in SBCCB.  I have also added the FPC connectors but it is not clear what the pin count is on them or which way the FPC cable connects.  This is important so that the mask openings face the correct direction.  The current changes are just my guesswork.  I'll let you know when the test case is ready, maybe later today still.
![star64_model](https://github.com/hominoids/SBC_Case_Builder/assets/37256300/3c05bb02-896e-4079-8920-fb9259ef053b)

**Comment by hominoids** [comment]
All the changes have been made on the Main branch of SBC Case Builder and I saved a test case called star64_shell.  When you have time, use that case for a test print so if any changes are needed I'll know what the SBCCB parameters were when printed.  You'll need to update SBCCB and it's submodule SBC Model Framework prior to printing.  
![Screenshot_2024-05-10_18-18-22](https://github.com/hominoids/SBC_Case_Builder/assets/37256300/3e8982ba-47a8-49b8-9df1-62a83afb046a)
FYI, I increased the case gap to 2mm to give more room and left the PCB thickness at the default 2mm.  The double stacked rj45 was too tall so I shortened it to 25mm.  The SBC maximum component height was also set incorrectly at 17mm which is why it protruded thru the case.  The SOC location is unknown to me so I approximated it's location.

I try to hold design tolerances to plus or minus 1/8mm so any warping or splitting of the print will effect the fit of the case.  Let me know how it went and what if any changes are needed.  Straight on photos of any problems will be helpful for the corrections.

**Comment by Fishwaldo** [comment]
when I render in openscad I get the following error:
```
Parsing design (AST generation)...
Compiling design (CSG Tree generation)...
ECHO: Case_Width = 135, Depth = 87.5, Top = 28, Bottom = 12
Rendering Polygon Mesh using CGAL...
Geometries in cache: 1352
Geometry cache size in bytes: 12553112
CGAL Polyhedrons in cache: 3
CGAL cache size in bytes: 77086416
Total rendering time: 0:10:28.746
   Top level object is a 3D object:
   Simple:         no
   Vertices:    40468
   Halfedges:  144858
   Edges:       72429
   Halffacets:  64750
   Facets:      32375
   Volumes:        13
WARNING: Object may not be a valid 2-manifold and may need repair! 
Rendering finished.
```


if I export to my printer it complains about a damaged STL.

**Comment by Fishwaldo** [comment]
Oh and PCB thickness is 0.9

**Comment by hominoids** [comment]
The Main branch and it's sub module have been updated with the new PCB thickness.  I changed the style of the SD card holder and also increased the size of the standoff support diameter to 14 for star64_shell.  At 13mm it was close to the side wall and was triggering a false positive manifold error.  OpenSCAD v21.1 complained but SuperSlicer v2.4.58.5 saw that it was indeed manifold.  The code for manifold detection isn't that sophisticated always.  I will likely add a blip about it in the README.md in the near future to warn users. Give it another try and let me know if there are any more problems.

**Comment by Fishwaldo** [comment]
Hi,
I did a test print today and it's almost perfect!

1) HDMI port needs to shift to the left (when looking at it directly) by about 1.5-2mm

![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/7a95f7f3-e38f-4f50-8f57-c09e5cfaa08a)

2) The Standoff are a bit misaligned on the side where the Ethernet port is. I hope you can see from this pic?
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/4e43eddd-537c-4224-a866-640db1017933)

3) (may be just due to me doing a fast print) - the thickness of the board means it's not a perfect fit between the top/bottom parts and leave a small gap around the joint (as seen on the first photo). The rest button and SD card are aligned perfectly.

**Comment by Fishwaldo** [comment]
Here is another shot of the HDMI

![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/b8378626-bb6c-46f7-9616-f06fc12d720e)

**Comment by Fishwaldo** [comment]
This doesn't bother me but if you want to center the FAN over the SOC, you can see its slight off in this pic:![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/88f2f37e-c8ad-4317-9758-5f098c3bf24f)
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/6d327aa6-8f66-4ffc-88bd-60ed97138c2d)

It needs to move down 5mm (centered?) and to the left 4mm when viewed with the Ethernet ports on the left of the pic.

**Comment by hominoids** [comment]
Ok, I made some more changes.  The HDMI was moved and the PCB thickness increased to 1.6.  I know you said 1mm but since there is a gap between the halves that cannot be right.  Most SBC are 1.6mm and that would make sense with what I'm seeing.  I also made a slight adjustment to the power connector and moved the PCB holes to 3.5mm from the corners.  FYI, The top fan opening is meant to be centered on the heatsink, not the SOC.  If you want it centered on the SOC we can disable the fan mask under the _Fan and Vent Openings_ Tab and create an accessory entry in sbc_case_builder_accessories.cfg for the new fan mask location with a subtractive entry. 
https://github.com/hominoids/SBC_Case_Builder#fan_mask
When you get a chance I could use the SOC size and location too. The location measurement should be from the lower left corner of the PCB to the lower left corner of the SOC with the PCB orientated so the RJ45 connectors are on the left. That would complete the model once we finish the final tweaks.
 
When there are no OEM drawings or models It usually takes me at least 2-3 test prints to get things zeroed in correctly, depending on how accurate I can measure things. You might consider doing the bottom test print first to see if the holes are correct, then the top if they are correct.  If they aren't, let me know ASAP and I'll adjust them accordingly, no point in wasting time and resources. Let me know how things go...were almost done. Thanks

**Comment by hominoids** [comment]
Just wanted to verify if the last adjustments worked out before I close this issue?  Does everything align?  If so, I'll mark the star64 as verified-green otherwise I'll leave it as yellow?

**Comment by Fishwaldo** [comment]
Sorry I haven't had a chance to do another print. I've started one now and will let you know soon.

**Comment by Fishwaldo** [comment]
Sorry I ran out of filament so only completed the print today. 

The mounting holes are still a bit off. I hope these pics are clear enough for you (I have one screw on the hole near the power connector)

![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/6504b4f4-e02f-49d2-b0c2-d78cb2e9b8e7)
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/aaa74444-46ef-4cec-982d-d11ce71b6d1a)
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/618e29c6-b55a-4357-bd59-a4829f4555bb)

**Comment by hominoids** [comment]
Ok, lets do this a different and more accurate way so not to waste any 
more of your time and filament.  Also, from the photo it looks like the 
PCB holes may not be located symmetrically in the corners, it's hard to 
tell.

First use your digital calipers to measure the inside diameter of the 
PCB hole.  Use the top set of gauges on the caliper that are designed 
for measuring inside diameters.  Then use the other set to measure the 
distance from the hole edge to the PCB edge in both the x and y axis, in 
case the hole isn't placed symmetrically.

Half the hole diameter plus the distance from the edge of the PCB to the 
edge of the hole will give us the exact location of the center of the 
hole from the corner.  If the x and y measurements for the PCB edge to 
hole edge are different, then the hole isn't placed systematically and 
I'll need to know both measurements and which measurement goes with 
which axis when the long side of the PCB board is orientated horizontal 
along the x-axis.  Check all four holes too just in case they aren't 
placed symmetrical to each other.  If measurements for all four holes 
are the same then I only need measurements from one of them. Thanks

**Comment by Fishwaldo** [comment]
Ok - Here we go:
hole diameter: 3.5mm
Hole A  - x side 2.66mm - y side - 2.5mm
Hole B - x side 2.66mm - y side -  2.5mm
Hole C - x side 2.66mm - y side - 2.8mm
Hole D - x side 2.66mm - y side - 2.65mm

y side width - 79.5mm
x side height - 127mm

**Comment by Fishwaldo** [comment]
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/35161d22-2fde-4163-a7b7-21195d08d586)

**Comment by hominoids** [comment]
The holes have been adjusted.

**Comment by hominoids** [comment]
I just received a very nice assortment of Pine64 SBC and one of them is a Star64.  You might want to hold off doing any test prints.  I'll start with the Star64 and after a good SBCCB test print let you know when it is ready.

**Comment by hominoids** [comment]
The Star64 model has been completed and a test case printed successfully.   Your hole measurements were spot on.  The Star64_shell saved case should be used which incorporates a 3mm gap.  It has a 40mm fan mask but you can change it to 25mm in the tab _Fan and Vent Openings_ -> fan size.   The case also uses 3mm inserts in the top standoffs which can be disabled if your not using them,  tab _SBC Top Standoff Global Settings_ -> top standoff insert.  If you disable them make sure to select the standoff and hole size you want.  I consider this complete and will close the issue, thanks for the help.
