### ISSUE TITLE
RPI 5 with Hats?

### ISSUE THREAD

**Issue by Fishwaldo** [hominoids/SBC_Case_Builder#36]
What's your recommendation for RPI5 with hats? I have a NVMe Hat for my rpi5 so just increase the height of the case? 

(In this model it also extends the GPIO headers above the HAT, it would be perfect if the top of the case had a cutout for the headers so they can be plugged in without disassembling the case (Like the case from Khadas in the pic below)

![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/eea5095a-70a3-4d57-8ad1-958e78fd9558)
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/6d4c75ca-6712-45ce-9466-4963d4b1db5c)
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/b9748593-56f7-4f1b-ab7a-dda928611073)
![image](https://github.com/hominoids/SBC_Case_Builder/assets/842308/edf0d369-dc2a-40ac-b657-062526478263)

**Comment by hominoids** [comment]
Yeah, that's basically it but the top standoffs need to be adjusted to accommodate the hat.  I've been meaning to model the recently released RPi M2 Hat so I did.  Since the basic footprint is the same it will work for your situation too.  I included a sample case called rpi5_m2hat_shell that can be used as is or as an example and starting point for you, take a look and let me know if it worked out ok.
![rpi5_m2hat_shell](https://github.com/hominoids/SBC_Case_Builder/assets/37256300/f4b263d6-a3b1-42d6-8688-7caa35f2b96e)
