### ISSUE TITLE
Increase height for additional HATs

### ISSUE THREAD

**Issue by sprange** [hominoids/SBC_Case_Builder#38]
Amazing project for OpenSCAD!  However for the life of me I can't figure out how to increase the case height.  My PI5 has a POE hat and a GPIO relay so I need a taller case.  I can't seem to find any parameter that affects the height of the case.  Any assistance would be great!

**Comment by hominoids** [comment]
The example case rpi5_m2hat_shell is based on the official RPI M2 hat which uses 16mm standoffs and has a PCB thickness of 1.65mm.  When using a third party hat both of these factors need to be taken into account as well as the actual additional height that might be needed for component clearance.

So lets say that the third party hat PCB thickness is the same(1.65mm) but uses 17mm standoffs instead of 16mm.  Lets also assume that 2mm more is needed for the third party hat component clearance.  That means we need to increase the top case height by 3mm and reduce the top standoff height by 2mm for our hypothetical third party hat to fit.  If the third party hat PCB thickness was different then we would also need to make an appropriate adjustment for the difference in PCB thickness, both in the case height and top standoffs. 

It might seem a little confusing at first but if you take your time and study the animation example I'm sure you'll understand whats going on and be able to apply it to your own situation.  I also realize that the 20mm standoff adjustment range may not work for some of the hats I've seen lately due to an increase in standoff and component height, so I just increased it to 30mm and pushed the update onto the main branch in case yours needs more adjustment then the previous 20mm allowed.

I'll leave this issue open through the weekend in case you have more questions but also let me know if everything worked out for you.
![hat_height_and_standoff_size_adjustment](https://github.com/hominoids/SBC_Case_Builder/assets/37256300/08b105e2-2511-41ca-bfa1-19f06817d9fc)

**Comment by hominoids** [comment]
lol, In my rush I got it wrong!  In the example above the top case standoffs only need to be reduced by 1mm not 2mm since the supplied hat standoffs increased from 16mm to 17mm.  The two millimeters was for the component clearance for a total case height increase of 3mm.

**Comment by sprange** [comment]
Ok totally makes sense.  I swear I tried 3D adjustments before asking but obviously not.  Thanks for taking the time to help me!
