### ISSUE TITLE
Suggestions for improving the program

### ISSUE THREAD

**Issue by Robocycle** [hominoids/SBC_Case_Builder#39]
Hi! I will immediately apologize for not knowing English, I wrote to you through a translator. I would like to thank you for such a wonderful program as "SBC Case Builder". I used it to create a case for my Rock 5b. In general, everything is fine, but there are two points that I would like to improve. These are just suggestions for improving your program. First: adding a parameter to the settings that would allow you to adjust the inner radius, in addition to "corner fillets". Something like "inner corner fillets". When creating a box, the wall thickness at the bend point is greater than the thickness of the straight wall. Because of this, when processing in a slicer, an additional line or point is added at the bend point. This is not very nice and increases the printing time.
![Corner](https://github.com/hominoids/SBC_Case_Builder/assets/172182923/e29d7059-643a-4210-a83c-cb4d2f7dbda4)
The "inner corner fillets" parameter would allow you to adjust the radius so that the bending thickness and the wall thickness are the same.
 Second: adding chamfering or rounding to the program settings at the junction of the racks ("standoff") and the bottom of the box instead of the cylindrical "standoff support". This results in a smooth transition and increases the strength of the racks ("standoff").
![Chamfer](https://github.com/hominoids/SBC_Case_Builder/assets/172182923/7b318d9b-d646-4a5a-875e-b12ad501291f)
With gratitude and respect to you, Robocycle.

**Comment by hominoids** [comment]
Hello,
Thank you for your suggestions.  Your right that the inner corner fillet is not calculated correctly. The premise of SBC Case Builder is autonomous case generation so instead of adding another entry in the user interface for an inner corner fillet, the code has been fixed to generate the correct thickness at the corners.  The wall thickness at the corner fillet is now the same thickness as the rest of the wall per this [commit](https://github.com/hominoids/SBC_Case_Builder/commit/29192ea4415a77698951c3d910ad52d300f1fdb7#diff-33e494c1031e1bfbf98ab9dc79b807b7ac1119a5e83db51fb407266ccdbfe630).

The second suggestion is more complex then what it appears.  The purpose of the "standoff support height" is to allow screw heads and nuts to be recessed in thin floors or ceilings that normally would not support the recess due to their thickness.  Tapering the support would interfere with the recess in some situations due to the reduction of the wall thickness at the recess caused by the taper.

![standoff_section](https://github.com/hominoids/SBC_Case_Builder/assets/37256300/d5d97aa4-7240-4b8c-b019-1892bda7ff1b)

For the bottom of most cases, the standoff support height needs to be kept as short as possible so as not to interfere with nearby PCB components.

The other problem with your suggestion is that the "standoff support height" is also used to create a deep recessed standoff for tall cases. This allows the use of significantly shorter fasteners and a tapered support would not allow this use.  Keeping its current cylinder form allows the most flexibility in my opinion. 

![deep_recessed_standoff](https://github.com/hominoids/SBC_Case_Builder/assets/37256300/e4a178e7-6fdd-42e9-a543-c45ce684e26a)

The third point I would make is that the "standoff sidewall support" provides better strength for standoffs then a tapered support approach. Standoff side wall support is available for all standoffs and it's position and length can be controlled per individual standoff.  The length of the side wall support is determined by the "standoff support diameter".

![standoff_sidewall_support](https://github.com/hominoids/SBC_Case_Builder/assets/37256300/9210fb6f-a22c-47d7-ad85-a257eb4da28d)

Here is an example of case that uses both methods.

![case_standoff_sidewall_support](https://github.com/hominoids/SBC_Case_Builder/assets/37256300/575c2025-dbf3-4953-856f-39e658cbf3d8)

Thanks for taking the time to make these suggestions and don't worry about having to use a translator, it worked well and I understood your suggestions.  I have fixed the corner fillet wall thickness and consider this issued closed. I'm glad that SBC Case Builder has been useful for you.
