### ISSUE TITLE
Cleanup Case Builder Config

### ISSUE THREAD

**Issue by davejlong** [hominoids/SBC_Case_Builder#5]
It seems like there's a number of elements of the Case Builder config file that aren't used or are potentially the wrong data type. I figured I'd create a list of them to make sure they aren't there for some future plan before submitting a PR to remove or change them:

* Remove standoff height (second element in all 4 of the standoff lists)
* Standoff reverse should be boolean (it seems like the checks are always boolean checks)
* Standoff insert enable should be a boolean

**Comment by hominoids** [comment]
The standoff reverse and standoff insert can be boolean but keep the standoff height for now.  It doesn't need to be in the customizer but keep it in the case schema(sbc_case_builder.cfg).  I have been working on decoupling the standoff height so it's not a calculation, in order to provide additional case flexibility.  On one hand keeping it as a calculation removes the user from having to figure it out and possibly make a mistake, but it also doesn't allow some case configurations.  I may be able to do the case config's with variable standoff height in the code base, and if so, it can be taken out later

**Comment by davejlong** [comment]
What if, instead of a standoff height, it's a modification to the calculated standoff? For example, if you want to add additional buffer space, perhaps to make room for a fan, you would just set the height to be the fan's size, and that value is added to the calculation?

**Comment by hominoids** [comment]
Extra z-axis is achieved by case_offset_bz already.  I think we will be going in the direction chosen by the decisions made regarding the customizer, see issue#7.
